name: Publish snapshots to maven

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 0.*
      - commit-metadata-poc

jobs:
  build-and-publish-snapshots:
    strategy:
      fail-fast: false
    #if: github.repository == 'opensearch-project/opensearch-spark'
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v3
        id: checkout

      # Capture the commit ID for metadata purposes
      - name: Set commit ID
        id: set_commit
        run: |
          COMMIT_ID=$(git log -1 --format='%H')
          echo "commit_id=${COMMIT_ID}" >> $GITHUB_OUTPUT
          echo "Using commit ID: ${COMMIT_ID}"

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Set up SBT
        uses: sbt/setup-sbt@v1

      # Create version.sbt file to override the version
      - name: Create version.sbt file
        run: |
          # Create version.sbt file with hardcoded version
          echo 'ThisBuild / version := "0.8.0-commit-metadata-poc-SNAPSHOT"' > version.sbt
          echo "Created version.sbt file:"
          cat version.sbt

      - name: Publish to Local Maven with hardcoded version
        run: |
          # Use -no-colors for cleaner logs
          sbt -no-colors clean standaloneCosmetic/publishM2
          sbt -no-colors clean sparkPPLCosmetic/publishM2
          sbt -no-colors clean sparkSqlApplicationCosmetic/publishM2
          
          # Verify the published artifacts have the correct version
          echo "Checking published artifacts:"
          find $HOME/.m2/repository/org/opensearch/ -name "*0.8.0-commit-metadata-poc-SNAPSHOT*" || echo "No artifacts found with the expected version"

      - uses: actions/checkout@v3
        with:
          repository: 'opensearch-project/opensearch-build-libraries'
          path: 'build'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.PUBLISH_SNAPSHOTS_ROLE }}
          aws-region: us-east-1

      - name: generate sha and md5
        run: |
          for i in `find $HOME/.m2/repository/org/opensearch/ -name "*.pom" -type f`; do sha512sum "$i" | awk '{print $1}' >> "$i.sha512"; done
          for i in `find $HOME/.m2/repository/org/opensearch/ -name "*.jar" -type f`; do sha512sum "$i" | awk '{print $1}' >> "$i.sha512"; done
          for i in `find $HOME/.m2/repository/org/opensearch/ -name "*.pom" -type f`; do sha256sum "$i" | awk '{print $1}' >> "$i.sha256"; done
          for i in `find $HOME/.m2/repository/org/opensearch/ -name "*.jar" -type f`; do sha256sum "$i" | awk '{print $1}' >> "$i.sha256"; done

      - name: Get credentials and publish snapshots to maven
        run: |
          export SONATYPE_USERNAME=$(aws secretsmanager get-secret-value --secret-id maven-snapshots-username --query SecretString --output text)
          export SONATYPE_PASSWORD=$(aws secretsmanager get-secret-value --secret-id maven-snapshots-password --query SecretString --output text)
          echo "::add-mask::$SONATYPE_USERNAME"
          echo "::add-mask::$SONATYPE_PASSWORD"
          export SNAPSHOT_REPO_URL="https://aws.oss.sonatype.org/content/repositories/snapshots/"
          cd build/resources/publish/
          cp -a $HOME/.m2/repository/* ./
          ./publish-snapshot.sh ./

      # NEW STEP: Upload modified metadata files after Maven deployment
      - name: Upload custom metadata with commit ID
        run: |
          # Get credentials to upload files directly
          export SONATYPE_USERNAME=$(aws secretsmanager get-secret-value --secret-id maven-snapshots-username --query SecretString --output text)
          export SONATYPE_PASSWORD=$(aws secretsmanager get-secret-value --secret-id maven-snapshots-password --query SecretString --output text)
          
          # For each project, create and upload a modified metadata file
          PROJECTS=("opensearch-spark-standalone_2.12" "opensearch-spark-ppl_2.12" "opensearch-spark-sql-application_2.12")
          
          for PROJECT in "${PROJECTS[@]}"; do
            echo "Processing metadata for ${PROJECT}"
          
            # Create a temporary metadata file with commit ID
            TEMP_DIR=$(mktemp -d)
            METADATA_FILE="${TEMP_DIR}/maven-metadata.xml"
          
            # Download the current metadata from the repository
            META_URL="https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/${PROJECT}/0.8.0-commit-metadata-poc-SNAPSHOT/maven-metadata.xml"
            echo "Downloading metadata from ${META_URL}"
            curl -s -u "${SONATYPE_USERNAME}:${SONATYPE_PASSWORD}" -o "${METADATA_FILE}" "${META_URL}"
          
            if [ -f "${METADATA_FILE}" ]; then
              # Modify the metadata to include commit ID
              cp "${METADATA_FILE}" "${METADATA_FILE}.bak"
          
              awk -v commit="${{ steps.set_commit.outputs.commit_id }}" '
                /<versioning>/ {
                  print $0
                  print "  <commitId>" commit "</commitId>"
                  next
                }
                {print}
              ' "${METADATA_FILE}.bak" > "${METADATA_FILE}"
          
              rm "${METADATA_FILE}.bak"
          
              echo "Modified metadata content:"
              cat "${METADATA_FILE}"
          
              # Upload the modified metadata back
              echo "Uploading modified metadata"
              curl -v -u "${SONATYPE_USERNAME}:${SONATYPE_PASSWORD}" --upload-file "${METADATA_FILE}" "${META_URL}"
          
              # Also upload to maven-metadata.xml in the parent directory
              PARENT_URL="https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/${PROJECT}/maven-metadata.xml"
              curl -s -u "${SONATYPE_USERNAME}:${SONATYPE_PASSWORD}" -o "${TEMP_DIR}/parent-metadata.xml" "${PARENT_URL}"
          
              if [ -f "${TEMP_DIR}/parent-metadata.xml" ]; then
                cp "${TEMP_DIR}/parent-metadata.xml" "${TEMP_DIR}/parent-metadata.xml.bak"
          
                awk -v commit="${{ steps.set_commit.outputs.commit_id }}" '
                  /<versioning>/ {
                    print $0
                    print "  <commitId>" commit "</commitId>"
                    next
                  }
                  {print}
                ' "${TEMP_DIR}/parent-metadata.xml.bak" > "${TEMP_DIR}/parent-metadata.xml"
          
                curl -v -u "${SONATYPE_USERNAME}:${SONATYPE_PASSWORD}" --upload-file "${TEMP_DIR}/parent-metadata.xml" "${PARENT_URL}"
              fi
            else
              echo "Failed to download metadata for ${PROJECT}"
            fi
          
            rm -rf "${TEMP_DIR}"
          done